language: python
python:
- '3.3'
- '3.4'
- '3.5'
install:
- python setup.py -q install
script:
- nosetests
deploy:
  provider: pypi
  user: Gohla
  password:
    secure: hV4ebHxDhtE2oobDOUh1oX2SLtJCrOFWQotXRtQjTgwzkGE5vlqq2AGjFyiDu7JPo8bROE3DnKvA+9F3PP4If27XwP1oa20uGyDebo0/B0ev1RhXK9gTlrgqj3ZpfTeO2wTF8qUH/hB4IeC6czXf06+yL8+wFpwYA68GjV1GkfPqufJfr1IcINyrrv9P4YxZIKtHnPJTCqHk/neuZ6CE/RN9ekG+EcYjsVxYfIWWUMwgGMX0JGZxL7/oW517UiLkCLXQK40BlpR/rbZ5RH5ewXf+Tmd5G5SJyF3n1tVu3RvspddcESAoVMflgFFMblwkZwMiQVraBMk5a0L3uX7sLpMnIFhVL6HmjPxTQuJw98L/dgIIlHzasYFxRtI6PuXCjfBQALYlDyVl/MAyZ27t0Lm1liXsJmqj6Kno73eUeHglGbOlsPswptzEOgPHygiL+scb6JjEozxpb8gyApiXGZeApRkyxpC1baew0vd02SrMyOlmjfJ9XerFpRPYIsKym8XUnPy8y5YmLYy92ZTN6MabJ5bm/0uqpkwFqgpezn+nXm/IOZkDILMH0Vro442a+uslk5AMdgFJ/BVn5qm3amiQ+u51IxmANkd1DRttL4fDEMGVGWJ3GYxoXbujRdtsoqC/vb9o4IEbpHiVFYDVOgzynQGxsJXqxtOE73i69c0=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Gohla/buildorchestra
